# Generated by Django 4.2.7 on 2025-12-05 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_detections', models.IntegerField(default=0)),
                ('plastic_count', models.IntegerField(default=0)),
                ('paper_count', models.IntegerField(default=0)),
                ('glass_count', models.IntegerField(default=0)),
                ('metal_count', models.IntegerField(default=0)),
                ('organic_count', models.IntegerField(default=0)),
                ('other_count', models.IntegerField(default=0)),
                ('total_points_awarded', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Detection statistics',
                'db_table': 'detection_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bin_id', models.UUIDField(help_text='ID of the bin where detection occurred')),
                ('user_qr_code', models.CharField(help_text='QR code of the user', max_length=100)),
                ('material_type', models.CharField(choices=[('plastic', 'Plastic'), ('paper', 'Paper'), ('glass', 'Glass'), ('metal', 'Metal'), ('organic', 'Organic'), ('other', 'Other')], max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='Detection confidence (0-1)')),
                ('points_awarded', models.IntegerField(default=0)),
                ('points_added_to_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'material_detections',
                'ordering': ['-created_at'],
            },
        ),
    ]
