# Generated by Django 4.2.7 on 2025-12-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_rename_user_qr_code_to_user_nfc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdetection',
            name='user_nfc_code',
            field=models.CharField(help_text='NFC code of the user', max_length=100),
        ),
    ]
