# Generated by Django 4.2.7 on 2025-12-05 13:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('qr_code', models.CharField(help_text='QR code on the bin', max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacity', models.IntegerField(default=100, help_text='Capacity in liters')),
                ('fill_level', models.IntegerField(default=0, help_text='Current fill level percentage')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Under Maintenance'), ('full', 'Full')], default='active', max_length=20)),
                ('is_open', models.BooleanField(default=False)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('last_emptied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_qr_code', models.CharField(help_text="User's QR code who used the bin", max_length=100)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('detection_completed', models.BooleanField(default=False)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='bins.bin')),
            ],
            options={
                'db_table': 'bin_usage_logs',
                'ordering': ['-opened_at'],
            },
        ),
    ]
