# Generated by Django 4.2.7 on 2025-12-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='nfc_tag_id',
            field=models.CharField(blank=True, help_text='Auto-generated NFC tag ID', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bin',
            name='qr_code',
            field=models.CharField(blank=True, help_text='Auto-generated unique bin ID', max_length=100, unique=True),
        ),
    ]
