# Generated by Django 4.2.7 on 2025-12-14 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_bin_nfc_tag_id_alter_bin_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='city',
            field=models.CharField(blank=True, help_text='City where the bin is located', max_length=100),
        ),
    ]
