# Generated by Django 4.2.7 on 2025-12-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0005_bin_current_capacity_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binusagelog',
            name='user_nfc_code',
            field=models.CharField(help_text="User's NFC code who used the bin", max_length=100),
        ),
    ]
