# Generated by Django 4.2.7 on 2025-12-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0006_alter_binusagelog_user_nfc_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bin',
            name='current_capacity_used',
        ),
    ]
