# Generated by Django 4.2.7 on 2025-12-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clerk_id',
            field=models.CharField(blank=True, help_text='Clerk authentication ID for hybrid auth support', max_length=255, null=True, unique=True),
        ),
    ]
