# Generated by Django 4.2.7 on 2025-12-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_clerk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=5, help_text='Points earned from proper waste disposal (new users start with 5 points)'),
        ),
    ]
