# Generated by Django 4.2.7 on 2025-12-22 10:21

from django.db import migrations


def update_existing_users_to_5_points(apps, schema_editor):
    """Update all existing users with 0 points to have 5 points"""
    User = apps.get_model('accounts', 'User')
    # Update users who have 0 points to 5 points
    User.objects.filter(points=0).update(points=5)


def reverse_update(apps, schema_editor):
    """Reverse migration - set users back to 0 points (optional)"""
    User = apps.get_model('accounts', 'User')
    # Only reverse if they have exactly 5 points (to avoid affecting users who earned points)
    User.objects.filter(points=5).update(points=0)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_set_default_points_to_5'),
    ]

    operations = [
        migrations.RunPython(update_existing_users_to_5_points, reverse_update),
    ]
