# Generated by Django 4.2.7 on 2025-12-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_existing_users_to_5_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='qr_code',
            new_name='nfc_code',
        ),
    ]
