# Generated by Django 4.2.7 on 2025-12-05 14:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_qr_code', models.CharField(help_text='QR code of the user submitting the reclamation', max_length=100)),
                ('bin_id', models.UUIDField(blank=True, help_text='ID of the bin (if applicable)', null=True)),
                ('reclamation_type', models.CharField(choices=[('full', 'Bin is Full'), ('broken', 'Bin is Broken'), ('missing', 'Bin is Missing'), ('overflow', 'Bin Overflowing'), ('odor', 'Bad Odor'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(help_text='Detailed description of the issue')),
                ('location', models.CharField(blank=True, help_text='Location description', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to user)')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reclamations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReclamationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(help_text='Path to uploaded file', max_length=500)),
                ('file_type', models.CharField(help_text='File MIME type', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reclamations.reclamation')),
            ],
            options={
                'db_table': 'reclamation_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
