# Generated by Django 4.2.7 on 2025-12-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reclamations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReclamationAttachment',
        ),
    ]
